from __future__ import annotations

import hashlib
import json
import time
from typing import Any, Dict, List

from online.policy.propose import propose_actions
from online.rm.value import score_action_batch


class BoNPlanner:
    def __init__(self, ckpt: str, device: str = "auto", max_len: int = 512, batch_size: int = 128):
        self.ckpt = str(ckpt)
        self.device = str(device)
        self.max_len = int(max_len)
        self.batch_size = int(batch_size)

    def plan_step(
        self,
        env,
        task_ctx,
        history,
        bon_n: int,
        rollout_horizon: int,
        seed: int,
    ) -> Dict[str, Any]:
        start = time.perf_counter()
        snap = env.snapshot()
        obs_text = env.get_observation_text()
        obs_hash = hashlib.sha256(obs_text.encode("utf-8")).hexdigest()

        actions = propose_actions(
            obs_text=obs_text,
            history=history,
            n=max(int(bon_n), 1),
            seed=int(seed),
            task_ctx=task_ctx,
        )
        if not actions:
            raise RuntimeError("No candidate actions generated by proposer.")

        score_items: List[Dict[str, Any]] = []
        sim_rows: List[Dict[str, Any]] = []
        horizon = max(int(rollout_horizon), 1)

        for action in actions:
            env.restore(snap)
            sim_action = dict(action)
            sim_action["delta_steps"] = horizon
            _, _, sim_done, sim_info = env.step(sim_action)
            sim_info = dict(sim_info or {})
            score_items.append(
                {
                    "instruction_refined": str(task_ctx.get("instruction_refined") or ""),
                    "trajectory_prefix_text": obs_text,
                    "action_text": str(action.get("action_text") or ""),
                    "rollout_text": str(sim_info.get("committed_text") or ""),
                }
            )
            sim_rows.append({"action": dict(action), "sim_done": bool(sim_done), "sim_info": sim_info})

        scores = score_action_batch(
            ckpt=self.ckpt,
            items=score_items,
            device=self.device,
            max_len=self.max_len,
            batch_size=self.batch_size,
        )

        candidates: List[Dict[str, Any]] = []
        action_by_id: Dict[str, Dict[str, Any]] = {}
        for row, score in zip(sim_rows, scores):
            act = row["action"]
            info = dict(row["sim_info"] or {})
            candidate_id = str(act.get("candidate_id") or "")
            action_by_id[candidate_id] = dict(act)
            patch_text = str(act.get("patch_text") or "")
            committed_text = str(info.get("committed_text") or "")
            candidates.append(
                {
                    "candidate_id": candidate_id,
                    "instance_id": str(act.get("instance_id") or ""),
                    "action_text": str(act.get("action_text") or ""),
                    "patch_chars": len(patch_text),
                    "rm_score": float(score),
                    "token_proxy": int(len(str(act.get("action_text") or "")) + len(patch_text) + len(committed_text)),
                    "sim_done": bool(row["sim_done"]),
                    "sim_info": {
                        "committed_steps_len": int(info.get("committed_steps_len", 0)),
                        "candidate_done": bool(info.get("candidate_done", False)),
                        "candidate_success": info.get("candidate_success"),
                        "patch_apply_ok": info.get("patch_apply_ok"),
                        "tests_passed": info.get("tests_passed"),
                        "exit_code": info.get("exit_code"),
                        "exec_error_type": info.get("exec_error_type"),
                    },
                }
            )

        ranked = sorted(candidates, key=lambda x: (-float(x["rm_score"]), str(x["candidate_id"])))
        selected = dict(ranked[0])

        env.restore(snap)
        commit_action = dict(action_by_id.get(str(selected["candidate_id"]), {}))
        commit_action["candidate_id"] = str(selected["candidate_id"])
        commit_action["delta_steps"] = int(commit_action.get("delta_steps", 1))
        _, _, env_done, env_info = env.step(commit_action)

        overhead_ms = (time.perf_counter() - start) * 1000.0
        return {
            "obs_hash": obs_hash,
            "candidates": candidates,
            "selected_candidate_id": str(selected["candidate_id"]),
            "selected_rm_score": float(selected["rm_score"]),
            "env_done": bool(env_done),
            "env_info": dict(env_info or {}),
            "planning_overhead_ms": float(overhead_ms),
            "total_rm_forward_calls": len(candidates),
            "_debug": {
                "seed": int(seed),
                "snapshot_size": len(snap),
                "selected": json.dumps(selected, ensure_ascii=False),
            },
        }
